# Generated by Django 3.1.7 on 2021-07-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210721_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile_pic.png', upload_to='profile_pictures'),
        ),
    ]
