# Generated by Django 3.1.7 on 2021-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210717_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/563be68403b50placeholder_food_item_2.png', max_length=500),
        ),
    ]
