# Generated by Django 3.1.7 on 2021-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210717_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/563be68403b50placeholder_food_item_2.png', max_length=550),
        ),
    ]
