# Generated by Django 3.1.7 on 2021-07-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210717_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/563be68403b50placeholder_food_item_2.png', max_length=500),
        ),
    ]
